### PR TITLE
Change social links to icons #94 and logos compression and resizing close #31

### LINKED ISSUE #31: WiKirby logo is 1/3 of the size of the main page
The whole main page is about 1 MB, and the wikirby logo is 360kB. It should be scaled down to a more reasonable size.

### PR DESCRIPTION
**Pull request by 41646F6C666F**
This replaces the social links (Facebook, Twitter, and Discord) in the members and affiliates listings by icons.

> Looking at the repos participating on the Hacktoberfest this year, I found your project and I couldn't resist giving you a hand.
This may not be the last PR, if you guys are up for more :shipit:

### CODE REVIEW

**Comment by 41646F6C666F** [comment]
Compressed and resized all the logos, from 2 Mo to 656 KB.

**Comment by KevinPayravi** [comment]
Thanks so much for the PR! Good start.

Two things while testing it out:
* Our current white Discord icon doesn't contrast with its background; we should replace it with one that preferably matches the style of the others (circle with Discord purple?). Or, all social media icons can be replaced with a another consistent design.
* Logo size reduction is great, though the resize to 100px may be too small. Currently we have 150px of room on the members+affiliate pages to display logos. Logos should be either 150px, or the members+affiliate page CSS should be changed to better fit 100px (along with centering the logos vertically). 100px could be nice to save space, though some of the logos are harder to read at smaller sizes - so I'm leaning towards keeping 150px.

Screenshot for reference:
Screen Shot 2022-10-08 at 12 25 00 AM

If it's easier to manage these changes separately, feel free to split into separate PRs.

Thanks again!

**Comment by 41646F6C666F** [comment]
Thank you, Kevin. 
100px is not right at all indeed, I messed up someways. 
I'll fix that right now, and search you guys a new discord icon too 😉

**Comment by 41646F6C666F** [comment]
Switching to PR #107.

**Pull request closed without merging**
